# Copyright (c) 2018 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# THIS CODE IS PROVIDED ON AN  *AS IS* BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
# LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
# FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
#
# See the Apache Version 2.0 License for specific language governing
# permissions and limitations under the License.
#

#ACL Configuration File
#Example of an ACL entry is below
#ACL Entries:
#        - block-unicast -A INPUT -p tcp -i e101-025-1 -d 20.1.1.2/255.255.255.255 -j DROP
#        - icmp-output -A INPUT -p icmp -i e101-011-0 -j DROP
#        - drops-pkt -A OUTPUT -o e101-011-0 -d 30.1.1.2/255.255.255.255 -j DROP
#        - block-syn -A INPUT -i e101-025-2 -p tcp --tcp-flags SYN,ACK -j DROP

ACL Entries:
